apiVersion: v1
kind: Pod
metadata:
  generateName: kaniko-builder-initial-
  labels:
    app: kaniko-builder
spec:
  containers:
    - name: kaniko-builder-initial
      image: "debian:11"
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 1000m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 100Mi
      env:
        - name: TZ
          value: Asia/Shanghai
      volumeMounts:
        - name: workspace
          mountPath: /workspace
          subPath: workspace
      command:
        - bash
        - -c
        - tail -f /dev/null
  volumes:
    - name: workspace
      persistentVolumeClaim:
        claimName: "{{ pvc }}"

  restartPolicy: Always
