apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  generateName: kaniko-builder-source-
  labels:
    app: kaniko-builder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
