# refer: https://github.com/GoogleContainerTools/kaniko#using-kaniko
apiVersion: v1
kind: Pod
metadata:
  generateName: kaniko-builder-
  labels:
    app: kaniko-builder
spec:
  # https://github.com/GoogleContainerTools/kaniko#caching
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.12.1
      imagePullPolicy: IfNotPresent
      args:
        {%- for mirror in mirrors %}
        - --registry-mirror={{ mirror }}
        {%- endfor %}
        {%- if insecurePull %}
        - --insecure-pull
        {%- endif %}
        - --context={{ context }}
        {%- if subpath %}
        - --context-sub-path={{ subpath }}
        {%- endif %}
        {%- if dockerfile %}
        - --dockerfile={{ dockerfile }}
        {%- endif %}
        {%- if buildarg %}
        - --build-arg={{ buildarg }}
        {%- endif %}
        {%- if git %}
        - --git={{ git }}
        {%- endif %}
        - --use-new-run
        - --cache=true
        - --cache-dir=/cache
        - --cache-run-layers
        - --compressed-caching=false
        # https://github.com/GoogleContainerTools/kaniko/issues/2065
        # https://github.com/GoogleContainerTools/kaniko/issues/1244
        - --cache-copy-layers=false
        - --skip-unused-stages
        - --single-snapshot
        - --snapshot-mode=redo
        - --skip-tls-verify-pull
        {%- if cacherepo %}
        - --cache-repo={{ cacherepo }}
        {%- endif %}
        {%- if insecure %}
        - --insecure
        {%- endif %}
        {%- for dest in destination %}
        - --destination={{ dest }}
        {%- endfor %}
        {%- if arg_cleanup %}
        - --cleanup
        {%- endif %}
        # - --label
        # - |
        #   org.opencontainers.image.authors=me@yinheli.com
        #   org.opencontainers.image.title=xxx
        #   org.opencontainers.image.description=xxx
        # - --destination=registry.default.svc:5000/app:v0.1.0
        # - --insecure
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
        {%- if pvc %}
        - name: workspace
          mountPath: /workspace
          subPath: workspace
        {%- endif %}
        - name: cache
          mountPath: /cache
          subPath: cache
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
  volumes:
    - name: kaniko-secret
      secret:
        secretName: dockercred
        items:
          - key: .dockerconfigjson
            path: config.json
    {%- if pvc %}
    - name: workspace
      persistentVolumeClaim:
        claimName: "{{ pvc }}"
    {%- endif %}
    - name: cache
      persistentVolumeClaim:
        claimName: kaniko-builder-cache

  restartPolicy: Never
